/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package leapyears;

public class LeapYear {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new LeapYear().getGreeting());
    }
}
