/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package leapyears;

import java.util.ArrayList;

public class LeapYears {
  public static Boolean isLeapYear(int year) {
    return (year % 400 == 0) || (year % 4 == 0 && year % 100 != 0);
  }

  public static ArrayList<Integer> getLeapYears(int startYear, int endYear) {
    ArrayList<Integer> allLeapYears = new ArrayList<>();

    for (int year = startYear; year <= endYear; year++) {
      if (isLeapYear(year)) {
        allLeapYears.add(year);
      }
    }

    return allLeapYears;
  }
}
