/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package leapyears;

public class LeapYears {
  public static Boolean isLeapYear(int year) {
    return (year % 400 == 0) || (year % 4 == 0 && year % 100 != 0);
  }
}
