/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package game;

import java.io.*;
import java.util.Scanner;

public class App {
    private final BufferedReader input;
    private final PrintStream output;
    private final Game game;

    public App(InputStream input, PrintStream output, Game game) {
        this.input = new BufferedReader(new InputStreamReader(input));
        this.output = output;
        this.game = game;
    }

    public static void main(String[] args) throws IOException {
        App app = new App(System.in, System.out, new Game(new WordChoser()));
        app.run();
    }

    public void run() throws IOException {
        output.println("Welcome! Today the word to guess is:");

        for (int i = 0; i < 3; i++) {
            output.println(game.getWordToGuess());
            output.printf("Enter one letter to guess (%d attempts remaining): \n", game.getRemainingAttempts());

            Character letter = input.readLine().charAt(0);
            Boolean result = game.guessLetter(letter);

            if (result) {
                output.println("Right!");
            } else {
                output.println("Wrong...");
            }
        }
    }
}