/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package game;

import org.junit.Before;
import org.junit.Test;

import java.io.*;
import java.util.ArrayList;

import static org.junit.Assert.assertEquals;
import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.when;

public class AppTest {

    private static final WordChoser wordChoser = mock(WordChoser.class);

    @Before
    public void setupTests() {
        when(wordChoser.getRandomWordFromDictionary()).thenReturn("AB");
    }

    @Test public void testGuessTwoLetterWord() throws IOException {
        String[] helper = helper("A\nC\nB");

        // show welcome message
        assertEquals("Welcome! Today the word to guess is:", helper[0]);

        // first loop
        assertEquals("A_", helper[1]);
        assertEquals("Enter one letter to guess (10 attempts remaining): ", helper[2]);
        assertEquals("Right!", helper[3]);

        // second loop
        assertEquals("Wrong...", helper[6]);

        // third loop
        assertEquals("Enter one letter to guess (9 attempts remaining): ", helper[8]);
        assertEquals("Right!", helper[9]);
    }

    private String[] helper(String userInput) throws IOException {
        ArrayList<Character> captured = new ArrayList<>();
        InputStream input = new ByteArrayInputStream(userInput.getBytes());
        OutputStream output = new OutputStream() {
            @Override
            public void write(int inByteValue) throws IOException {
                captured.add((char) inByteValue);
            }
        };

        App app = new App(input, new PrintStream(output), new Game(wordChoser));
        app.run();
        String str = captured.stream()
                .map(e->e.toString())
                .reduce((acc, e) -> acc  + e)
                .get();
        String[] lines = str.split("\\r?\\n");
        return lines;
    }
}
