/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package change_converter;

import java.math.BigDecimal;
import java.text.NumberFormat;
import java.util.ArrayList;
import java.util.Locale;

public class ChangeGenerator {

    public static ArrayList<String> convert(Float value) {
        String formattedValue = String.format("£%.0f", value);

        ArrayList<String> notesAndCoins = new ArrayList<>();
        notesAndCoins.add(formattedValue);

        return notesAndCoins;
    }
}
